## PhenoCam ROI: An interactive Region of Interest (ROI) delineator for the PhenoCam database

In order to extract time series data from a series of images, one needs to 1) delineate a region of interest (ROI); 2) create a mask file identifying pixles of interest; and 3) calculate averaged values of particular bands (e.g. Green Chromatic Coordinate or GCC) over a time period. However, these steps are painstaking and need special accuracy. The PhenoCam ROI tool provides an interactive web interface to facilitate these process of large imagery datasets. This document is a simple guide to explain different elements of the PhenoCam ROI and their functionality.

### Easiest way is to use runGitHub
The following command will check for all the required R packages, install them if needed and run the drawROI app directly from GitHub. However, latest version of R should be already installed. The app requires pre-installed GDAL and basic image rendering libraries (png, jpeg, tif, etc.) on the operating system.

```{r, echo=TRUE}

library(shiny)

runGitHub("drawROI", "bnasr")

```


The R package is developed and maintained by [Bijan Seyednarollah](https://github.com/bnasr) since April, 2017.

Most recent release is available from: https://github.com/bnasr/drawROI
